import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		// as a root layout, it should contain html and body tags
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
